export const LOGIN = 'LOGIN';
export const SET_FORM_LOGIN = 'SET_FORM_LOGIN';
export const SET_FORM_REGISTER = 'SET_FORM_REGISTER';
export const SET_FORM_FORGOT_PASSWORD = 'SET_FORM_FORGOT_PASSWORD';
export const SET_FORM_RESET_PASSWORD = 'SET_FORM_RESET_PASSWORD';
export const SET_FORM_DATA_PESERTA = 'SET_FORM_DATA_PESERTA';